service: graphql-resume

frameworkVersion: ">=1.9.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  devCognitoPool: ${file(arn.json):cognitoPool.dev}
  prodCognitoPool: ${file(arn.json):cognitoPool.prod}

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  environment:
    RESUME_DB: {Ref: ResumeDB}
  iamRoleStatements:
    - Effect: Allow
      Resource:
        - "Fn::Join":
            - ""
            - - "arn:aws:dynamodb:"
              - {Ref: "AWS::Region"}
              - ":"
              - {Ref: "AWS::AccountId"}
              - ":table/"
              - Ref: ResumeDB
        - "Fn::Join":
            - ""
            - - "arn:aws:dynamodb:"
              - {Ref: "AWS::Region"}
              - ":"
              - {Ref: "AWS::AccountId"}
              - ":table/"
              - Ref: ResumeDB
              - '/index/*'
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query

functions:
  test-auth:
    handler: src/test-auth.handler
    events:
      - http:
          cors: true
          authorizer:
            name: pool_auth
            arn: '${self:custom.${self:custom.stage}CognitoPool}'
          path: /test-auth
          method: get
  graph-ql:
    handler: src/graph-ql.handler
    events:
      - http:
          cors: true
          authorizer:
            name: pool_auth
            arn: '${self:custom.${self:custom.stage}CognitoPool}'
          path: /graph-ql
          method: post
      - http:
          cors: true
          path: /read-graph-ql
          method: post

resources:
  Resources:
    ResumeDB: ${file(resources/resume-db.yml)}

package:
  exclude:
    - bin/**
    - resources/**
    - package.json
    - notes.txt
    - node_modules/**
  include:
    - node_modules/uuid/**
    - node_modules/lodash/**
    - node_modules/graphql/**
    - node_modules/iterall/**