AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation Template for Initializing S3 Buckets

Parameters:
  Region:
    Type: String
    Default: us-west-2
  TimeStamp:
    Type: String
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev
    Description: Stage
  ServiceName:
    Type: String
    Default: graphql-resume

Mappings:
  LambdasBucketMap:
    dev:
      Name: '{{resolve:ssm:graphql-resume-dev-lambdas-bucket:1}}'
    prod:
      Name: '{{resolve:ssm:graphql-resume-prod-lambdas-bucket:1}}'

Resources:
  LambdasBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::FindInMap:
          - LambdasBucketMap
          - Ref: Stage
          - Name
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
